#!/usr/bin/env bash

# Define toolbox directory
TOOLBOX="$HOME/.exolnet/toolbox"

echo "Installing homebrew ..."
echo

if [[ -z $(command -v brew) ]]; then
    # Homebrew will install the Command Line Tools, no need to run `xcode-select --install` beforehand
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    echo
fi

echo "Cloning exolnet-macos-toolbox ..."
echo

# Clone exolnet-macos-toolbox
git clone -b master https://github.com/eXolnet/exolnet-macos-toolbox.git $TOOLBOX
cd $TOOLBOX

echo
echo "Installing exolnet-macos-toolbox ..."

# Install exolnet-macos-toolbox
./install
