#!/usr/bin/env bash

# Define toolbox directory
TOOLBOX="$HOME/.exolnet/toolbox"

echo "Cloning exolnet-macos-toolbox ..."
echo

# Clone exolnet-macos-toolbox
git clone -b master https://github.com/eXolnet/exolnet-macos-toolbox.git $TOOLBOX
cd $TOOLBOX

echo
echo "Installing exolnet-macos-toolbox ..."

# Install exolnet-macos-toolbox
./install
