#!/usr/bin/env bash

e_header "Uninstalling deprecated php versions"
brew_is_installed php@5.6 && brew_uninstall php@5.6
brew_is_installed php@7.0 && brew_uninstall php@7.0
brew_is_installed php@7.1 && brew_uninstall php@7.1
