#!/usr/bin/env bash

HTTPD_ETC="/usr/local/etc/httpd"
HTTPD_WWW="/usr/local/var/www"
HTTPD_SSL="$HTTPD_ETC/exolnet-ssl"

function httpd_disable_mpm_event_module()
{
    /usr/bin/sed -i '' 's/^\(LoadModule mpm_event_module .*\)$/#\1/g' $HTTPD_ETC/httpd.conf
}

function httpd_enable_mpm_prefork_module()
{
    /usr/bin/sed -i '' 's/^#\(LoadModule mpm_prefork_module .*\)$/\1/g' $HTTPD_ETC/httpd.conf
}

DEVELOPMENT_PREFERENCES=$(read_preferences development)

if [[ " ${DEVELOPMENT_PREFERENCES[@]} " =~ " apache " ]]; then
    e_header "Installing and configuring apache with ssl"
    sudo_brew_is_status httpd stopped || sudo_brew_stop httpd
    backup_file "$HTTPD_ETC/exolnet-vhosts"
    create_directory "$HOME/Sites"
    brew_install httpd
    brew_install mkcert
    brew_install nss
    create_directory "$HTTPD_SSL/localhost"
    safe_execute "mkcert_install_local_ca" "Installed local certificate authority" "Failed to install local certificate authority"
    safe_execute "mkcert_generate_ssl_certificate" "Generated localhost ssl certificate" "Failed to generate localhost ssl certificate"
    safe_execute "httpd_replace_listen_80" "Changed listen port 8080 -> 80" "Failed to change listen port 8080 -> 80"
    safe_execute "httpd_replace_listen_443" "Changed listen port 8443 -> 443" "Failed to change listen port 8443 -> 443"
    safe_execute "httpd_disable_mpm_event_module" "Disabled mpm event module in httpd" "Failed to disable mpm event module in httpd"
    safe_execute "httpd_enable_mpm_prefork_module" "Enabled mpm prefork module in httpd" "Failed to enable mpm prefork module in httpd"
    create_directory "$HTTPD_ETC/exolnet"
    create_directory "$HTTPD_ETC/exolnet-vhosts"
    safe_execute "httpd_add_include_exolnet" "Added exolnet include directive" "Failed to add exolnet include directive"
    process_recursive "link_file" "$TOOLBOX/conf/httpd" "$HTTPD_ETC/exolnet"
    process_recursive "link_file" "$TOOLBOX/conf/httpd_vhosts" "$HTTPD_ETC/exolnet-vhosts"
    safe_execute "httpd_generate_user_conf" "Generated user conf file" "Failed to generate user conf file"
    link_file "$HOME/Sites" "$HTTPD_WWW"

    if [[ " ${DEVELOPMENT_PREFERENCES[@]} " =~ " mailhog " ]]; then
        link_file "$TOOLBOX/conf/httpd_vhosts_extra/750-mailhog.conf" "$HTTPD_ETC/exolnet-vhosts/750-mailhog.conf"
    fi

    sudo_brew_restart httpd
fi
