#!/usr/bin/env bash

function mysql57_list_all_databases()
{
    local list="$1"

    mysql --user=root --socket=/tmp/mysql@5.7.sock -sN -e "SHOW DATABASES" | egrep -v "information_schema|performance_schema|mysql|sys" > "$list"
}

function mysql57_dump_all_databases()
{
    local list="$1"
    local archive="$2"

    mysqldump --user=root --socket=/tmp/mysql@5.7.sock --force --opt --databases $(cat "$list" | tr '\n' ' ') > "$archive"
}

function mysql57_drop_all_databases()
{
    local list="$1"

    cat "$list" | awk '{print "DROP DATABASE `" $1 "`;"}' | mysql --user=root --socket=/tmp/mysql@5.7.sock
}

function mysql80_import_sql()
{
    local archive="$1"

    mysql --user=root --socket=/tmp/mysql@8.0.sock < "$archive"
}

# Read preferences
DEVELOPMENT_PREFERENCES=$(read_preferences development)

if [[ "${DEVELOPMENT_PREFERENCES[@]}" =~ "mysql" ]]; then
    e_header "Migrating databases from MySQL 5.7 to 8.0"

    if [[ ! (" ${DEVELOPMENT_PREFERENCES[@]} " =~ " mysql57 " && " ${DEVELOPMENT_PREFERENCES[@]} " =~ " mysql80 ") ]]; then
        e_error "Either one of MySQL 5.7 or MySQL 8.0 is not installed"
        e_arrow "Run 'exo-software-select' and 'exo-software-install' to install both MySQL 5.7 and MySQL 8.0, and then run exo-self-migrate again"
        exit 1
    fi

    brew_stop_all_mysql
    brew_start_mysql 5.7
    mysql_wait_for_connection 5.7
    brew_start_mysql 8.0
    mysql_wait_for_connection 8.0

    temp_dir="$(mktemp -d)"
    list="${temp_dir}/databases-list.txt"
    archive="${temp_dir}/databases.sql"

    safe_execute "mysql57_list_all_databases $list" "Listed all databases from MySQL 5.7" "Failed to list all databases from MySQL 5.7"
    safe_execute "mysql57_dump_all_databases $list $archive" "Exported all databases from MySQL 5.7" "Failed to export all databases from MySQL 5.7"
    safe_execute "mysql80_import_sql $archive" "Imported all databases to MySQL 8.0" "Failed to import all databases to MySQL 8.0"
    safe_execute "gzip $archive" "Compressed archive file" "Failed to compress archive file"
    backup_file "${archive}.gz"
    safe_execute "mysql57_drop_all_databases $list" "Dropped all databases from MySQL 5.7" "Failed to drop all databases from MySQL 5.7"
    backup_file "${list}"

    e_header "Caveats"
    e_arrow "All your MySQL 5.7 databases have been moved to MySQL 8.0"
    e_arrow "Port 3306 is now pointing to MySQL 8.0 and port 3307 to MySQL 5.7"
    e_arrow "Both unix socket paths remain unchanged"
fi
