#!/usr/bin/env bash

function apache_purge_php74_include_conf()
{
    if [[ -d "$HTTPD_ETC/exolnet-include" ]]; then
        grep -rl "php7.4-fpm.conf" "$HTTPD_ETC/exolnet-include" | while read -r file ; do
            backup_file "$file"
        done
    fi
}

e_header "Uninstalling deprecated php versions"
backup_file_if_exists "$HOME/Sites/php74"
apache_purge_php74_include_conf
backup_file_if_exists "$HTTPD_ETC/exolnet-php-fpm/php7.4-fpm.conf"
brew_is_installed php@7.4 && brew_uninstall php@7.4
