#!/usr/bin/env bash

DEVELOPMENT_PREFERENCES=$(read_preferences development)

if [[ " ${DEVELOPMENT_PREFERENCES[@]} " =~ " mysql " ]]; then
    if command -v mysql; then
        e_header "Migrate from mysql_native_password to caching_sha2_password"
        local mysql="$(mysql_get_cli_command)"


        $mysql -e 'ALTER USER IF EXISTS "exolnet_dev"@"localhost" IDENTIFIED WITH caching_sha2_password BY ""' && \
        $mysql -e 'ALTER USER IF EXISTS "exolnet_local"@"localhost" IDENTIFIED WITH caching_sha2_password BY ""' && \
        $mysql -e 'ALTER USER IF EXISTS "exolnet_prev"@"localhost" IDENTIFIED WITH caching_sha2_password BY ""' && \
        $mysql -e 'ALTER USER IF EXISTS "exolnet_prod"@"localhost" IDENTIFIED WITH caching_sha2_password BY ""' && \
        $mysql -e 'ALTER USER IF EXISTS "exolnet_qa"@"localhost" IDENTIFIED WITH caching_sha2_password BY ""' && \
        $mysql -e 'ALTER USER IF EXISTS "exolnet_test"@"localhost" IDENTIFIED WITH caching_sha2_password BY ""'
    fi

    if brew_is_installed mysql; then
        e_header "Removing mysql"
        brew_stop mysql
        waiting_for 10
        backup_copy_file "$HOMEBREW_PREFIX/var/mysql"
        brew_uninstall mysql
    fi

    e_header "Installing mysql 8.4"
    brew_update
    brew_install mysql@8.4
    brew_link_force mysql@8.4
    brew_restart mysql@8.4
    mysql_wait_for_connection
fi
