#!/usr/bin/env bash

# Read preferences
DEVELOPMENT_PREFERENCES=$(read_preferences development)

if [[ " ${DEVELOPMENT_PREFERENCES[@]} " =~ " node " ]]; then
    e_header "Installing node@18"
    brew_is_installed node@18 && brew_uninstall node@18
    brew_install node@22
    brew_link_force node@22
fi
