#!/usr/bin/env bash

function redis_rename_preference_to_valkey()
{
    rename_stored_preference_key development redis valkey
}

function redis_dump_data()
{
    redis-cli --rdb "$1" > /dev/null
}

function valkey_get_dump_dir()
{
    valkey-cli config get dir | tail -1
}

# Read preferences
DEVELOPMENT_PREFERENCES=$(read_preferences development)

if [[ " ${DEVELOPMENT_PREFERENCES[@]} " =~ " redis " ]]; then
    if brew_is_installed redis; then
        REDIS_DUMP_FILE=$(mktemp -t redis-to-valkey)

        e_header "Migrating data from redis to valkey"
        brew_is_status redis started || brew_start redis
        safe_execute "redis_dump_data $REDIS_DUMP_FILE" "Dumped redis data" "Failed to dump redis data"

        e_header "Uninstalling redis"
        brew_is_status redis started && brew_stop redis
        safe_execute "brew_uninstall redis" "Uninstalled redis" "Failed to uninstall redis"

        e_header "Installing valkey"
        safe_execute "brew_install valkey" "Installed valkey" "Failed to install valkey"

        e_header "Starting valkey"
        safe_execute "brew_start valkey" "Started valkey" "Failed to start valkey"

        VALKEY_DUMP_DIR=$(valkey_get_dump_dir)

        e_header "Stopping valkey"
        safe_execute "brew_stop valkey" "Stopped valkey" "Failed to stop valkey"

        e_header "Importing dump into valkey"
        safe_execute "mv $REDIS_DUMP_FILE $VALKEY_DUMP_DIR/dump.rdb" "Imported dump into valkey" "Failed to import dump into valkey"

        e_header "Starting valkey"
        safe_execute "brew_start valkey" "Started valkey" "Failed to start valkey"
    else
        e_header "Installing valkey"
        safe_execute "brew_install valkey" "Installed valkey" "Failed to install valkey"

        e_header "Starting valkey"
        safe_execute "brew_restart valkey" "Started valkey" "Failed to start valkey"
    fi

    e_header "Renaming preference redis to valkey"
    safe_execute "redis_rename_preference_to_valkey" "Renamed preference redis to valkey" "Failed to rename preference redis to valkey"
fi
