#!/usr/bin/env bash

function gem_install()
{
    local gem=$@

    safe_execute "sudo gem install -n $HOMEBREW_PREFIX/bin $gem" "Installed $gem" "Failed to install $gem"
}

function _gem()
{
    yes | sudo gem "$@"
}

function gem_uninstall()
{
    local gem=$@

    safe_execute "_gem uninstall -n $HOMEBREW_PREFIX/bin $gem" "Uninstalled $gem" "Failed to uninstall $gem"
}
