#!/usr/bin/env bash

HTTPD_ETC="/usr/local/etc/httpd"
HTTPD_WWW="/usr/local/var/www"

function httpd_replace_listen_80()
{
    /usr/bin/sed -i '' 's/^Listen.*$/Listen 80/g' $HTTPD_ETC/httpd.conf
}

function httpd_replace_listen_443()
{
    /usr/bin/sed -i '' 's/^Listen.*$/Listen 443/g' $HTTPD_ETC/extra/httpd-ssl.conf
}

function httpd_add_include_exolnet()
{
    remove_insert_from_file $HTTPD_ETC/httpd.conf

cat >> $HTTPD_ETC/httpd.conf <<EOL
# EXOLNET-MACOS-TOOLBOX BEGIN
Include /usr/local/etc/httpd/exolnet/*
Include /usr/local/etc/httpd/exolnet-vhosts/*
# EXOLNET-MACOS-TOOLBOX END
EOL
}

function httpd_generate_user_conf()
{
    remove_insert_from_file $HTTPD_ETC/exolnet/user.conf

cat >> $HTTPD_ETC/exolnet/user.conf <<EOL
# EXOLNET-MACOS-TOOLBOX BEGIN
<IfModule unixd_module>
    User $(whoami)
    Group staff
</IfModule>
# EXOLNET-MACOS-TOOLBOX END
EOL
}

function httpd_disable_mpm_event_module()
{
    /usr/bin/sed -i '' 's/^\(LoadModule mpm_event_module .*\)$/#\1/g' $HTTPD_ETC/httpd.conf
}

function httpd_enable_mpm_prefork_module()
{
    /usr/bin/sed -i '' 's/^#\(LoadModule mpm_prefork_module .*\)$/\1/g' $HTTPD_ETC/httpd.conf
}

function httpd_disable_php_module()
{
    /usr/bin/sed -i '' 's/^\(LoadModule php[57]_module .*\)$/#\1/g' $HTTPD_ETC/httpd.conf
}
