#!/usr/bin/env bash

if [[ -z "$TOOLBOX_LIB_INCLUDED" ]]; then
    . $TOOLBOX/lib/header
    . $TOOLBOX/lib/utils
    . $TOOLBOX/lib/preferences
    . $TOOLBOX/lib/git
    . $TOOLBOX/lib/brew
    . $TOOLBOX/lib/mysql
    . $TOOLBOX/lib/httpd
    . $TOOLBOX/lib/php
    . $TOOLBOX/lib/node
    . $TOOLBOX/lib/completion

    TOOLBOX_LIB_INCLUDED=true
fi
