#!/usr/bin/env bash

function increase_sudo_timeout()
{
    echo 'Defaults	timestamp_timeout=60' | (sudo EDITOR=tee visudo -f /private/etc/sudoers.d/increase_sudo_timeout)
}

function enable_sudo_touch_id()
{
    # This line is a safeguard to prevent adding the same line over and over if it ever changes in the future
    grep -q 'pam_tid.so' /private/etc/pam.d/sudo && ! grep -q '^auth       sufficient     pam_tid.so$' /private/etc/pam.d/sudo && return 1

    # This line add the pam_tid.so entry to the pam sudo configuration file
    egrep -q '^auth       sufficient     pam_tid.so$' /private/etc/pam.d/sudo || (sudo /usr/bin/sed -i '' '1 a\
auth       sufficient     pam_tid.so\
' /private/etc/pam.d/sudo)

    # This line validates that the line was properly added
    grep -q '^auth       sufficient     pam_tid.so$' /private/etc/pam.d/sudo
}

function enable_require_password()
{
    defaults write com.apple.screensaver askForPassword -int 1
}

function set_require_password_to_immediately()
{
    defaults write com.apple.screensaver askForPasswordDelay -int 0
}

function enable_full_keyboard_access()
{
    defaults write NSGlobalDomain AppleKeyboardUIMode -int 2
}

function enable_show_all_file_name_extensions()
{
    defaults write NSGlobalDomain AppleShowAllExtensions -bool true
}
