#!/usr/bin/env bash

MYSQL_ETC="/usr/local/etc"

function mysql_get_cli_command()
{
    echo "mysql --user=root"
}

function mysql_create_users()
{
    local mysql="$(mysql_get_cli_command)"

    $mysql -e 'CREATE USER IF NOT EXISTS "exolnet_dev"@"localhost" IDENTIFIED WITH mysql_native_password' && \
    $mysql -e 'CREATE USER IF NOT EXISTS "exolnet_local"@"localhost" IDENTIFIED WITH mysql_native_password' && \
    $mysql -e 'CREATE USER IF NOT EXISTS "exolnet_prev"@"localhost" IDENTIFIED WITH mysql_native_password' && \
    $mysql -e 'CREATE USER IF NOT EXISTS "exolnet_prod"@"localhost" IDENTIFIED WITH mysql_native_password' && \
    $mysql -e 'CREATE USER IF NOT EXISTS "exolnet_qa"@"localhost" IDENTIFIED WITH mysql_native_password' && \
    $mysql -e 'CREATE USER IF NOT EXISTS "exolnet_test"@"localhost" IDENTIFIED WITH mysql_native_password'
}

function mysql_grant_users()
{
    local mysql="$(mysql_get_cli_command)"

    $mysql -e 'GRANT ALL PRIVILEGES ON `%\_dev`.* to "exolnet_dev"@"localhost"' && \
    $mysql -e 'GRANT ALL PRIVILEGES ON `%\_local`.* to "exolnet_local"@"localhost"' && \
    $mysql -e 'GRANT ALL PRIVILEGES ON `%\_prod`.* to "exolnet_prev"@"localhost"' && \
    $mysql -e 'GRANT ALL PRIVILEGES ON `%\_prod`.* to "exolnet_prod"@"localhost"' && \
    $mysql -e 'GRANT ALL PRIVILEGES ON `%\_qa`.* to "exolnet_qa"@"localhost"' && \
    $mysql -e 'GRANT ALL PRIVILEGES ON `%\_test`.* to "exolnet_test"@"localhost"'
}

function mysql_wait_for_connection()
{
    local mysql="$(mysql_get_cli_command)"

    echo -n -e "$INDENT \033[1m?\033[0m Waiting for mysql to be online "
    while ! $mysql -e 'SELECT USER()' &> /dev/null ; do
        echo -n '.' && sleep 1
    done
    echo -e "\r$INDENT \033[1;32m✔\033[0m Connected to mysql                                        "
}

function mysql_configure_mysqldump()
{
    local file="$HOME/.my.cnf"

    touch $file

    remove_insert_from_file $file

cat >> $file <<EOL
# EXOLNET-MACOS-TOOLBOX BEGIN
[mysqldump]
column-statistics = 0
# EXOLNET-MACOS-TOOLBOX END
EOL
}

function mysql_disable_binlog()
{
    local file="$MYSQL_ETC/my.cnf"

    remove_insert_from_file $file

cat >> $file <<EOL
# EXOLNET-MACOS-TOOLBOX BEGIN
disable-log-bin
# EXOLNET-MACOS-TOOLBOX END
EOL
}

function brew_stop_all_mysql()
{
    if brew_is_installed mysql@5.7 ; then
        brew_is_status mysql@5.7 stopped || brew_stop mysql@5.7
    fi
    if brew_is_installed mysql@8.0 ; then
        brew_is_status mysql stopped || brew_stop mysql@8.0
    fi
}

function brew_unlink_all_mysql()
{
    brew_is_installed mysql@5.7 && brew_unlink mysql@5.7
    brew_is_installed mysql@8.0 && brew_unlink mysql@8.0
}
