#!/usr/bin/env bash

function npm_global_install()
{
    local package=$@

    safe_execute "npm install -g $package" "Installed $package" "Failed to install $package"
}

function corepack_enable_yarn()
{
    [ -L "$HOMEBREW_PREFIX/bin/yarn" ] && rm -f "$HOMEBREW_PREFIX/bin/yarn"
    [ -L "$HOMEBREW_PREFIX/bin/yarnpkg" ] && rm -f "$HOMEBREW_PREFIX/bin/yarnpkg"
    corepack enable yarn
}

function corepack_prepare_yarn_stable()
{
    corepack prepare yarn@3 --activate
}

function yarn_enable_global_cache()
{
    yarn config set enableGlobalCache true --home
}
