#!/usr/bin/env bash

function npm_global_install()
{
    local package=$@

    safe_execute "npm install -g $package" "Installed $package" "Failed to install $package"
}

function corepack_enable_yarn()
{
    corepack disable yarn && corepack enable yarn
}

function corepack_prepare_yarn_stable()
{
    corepack prepare yarn@3 --activate
}

function yarn_enable_global_cache()
{
    yarn config set enableGlobalCache true --home
}
