#!/usr/bin/env bash

function pip3_install()
{
    local package=$@

    safe_execute "pip3 install $package" "Installed $package" "Failed to install $package"
}

function pip3_upgrade()
{
    local package=$@

    safe_execute "pip3 install --upgrade $package" "Upgraded $package" "Failed to upgrade $package"
}

function pip_install_system_boto()
{
    safe_execute "sudo /usr/bin/python -m easy_install pip" "Installed system pip" "Failed to install system pip"
    safe_execute "sudo /usr/bin/python -m pip install boto" "Installed system boto" "Failed to install system boto"
}
