#!/usr/bin/env bash

function pip3_install()
{
    local package=$@

    safe_execute "pip3 install $package" "Installed $package" "Failed to install $package"
}

function pip3_upgrade()
{
    local package=$@

    safe_execute "pip3 install --upgrade $package" "Upgraded $package" "Failed to upgrade $package"
}

function pip3_uninstall()
{
    local package=$@

    safe_execute "pip3 uninstall -y $package" "Uninstalled $package" "Failed to uninstall $package"
}
